In [7]:
import re
import os
import csv
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

In [8]:
def read_particle_positions(filename):
    positions = []
    with open(filename, 'r') as csvfile:
        csvreader = csv.reader(csvfile)
        next(csvreader)  # Skip header row
        for row in csvreader:
            positions.append([float(row[0]), float(row[1]), float(row[2])])
    return positions

In [11]:
directory = './output/default_simulation_params/'  # Directory containing CSV files
files = sorted([f for f in os.listdir(directory) if f.startswith('particle_positions')])

filename = directory.replace('./output/','').replace('/','.txt')
print(filename)

parameters = {}
with open(filename, 'r') as file:
    for line in file:
        # Use regular expressions to match lines with parameter values
        match = re.match(r'^(\w+)\s*:\s*(.+)$', line)
        if match:
            key = match.group(1)
            value = match.group(2)
            parameters[key] = value
print(parameters)

Nbody = 3
Ndim = 3
Nstep = 50
positions = np.empty((Nbody,Ndim,Nstep))

for f_index, file in enumerate(files):
    line = read_particle_positions(os.path.join(directory, file))
    for index in range(len(line)):
        positions[index,:,f_index] = line[index]
        print(positions[index,:,f_index])

default_simulation_params.txt
{'Cosmology': 'False', 'Halo_finder': 'False', 'Save_output': 'True', 'N_steps': '50', 'N_particles': '3', 'M_particles': '15', 'V_prt_init_max': '2', 'L_box': '10', 'Hubble_Param': '0.7', 'Omega_m': '0.3', 'Omega_Lambda': '0.7', 'N_bins_hf': '50 '}
[1.226033 7.460432 4.487442]
[6.703352 9.263548 3.735712]
[ 5.20467   6.612831 -0.014668]
[1.136689 7.364812 4.388383]
[6.613741 9.180168 3.636404]
[ 5.112339  6.514168 -0.106319]
[1.047344 7.269191 4.289324]
[6.524129 9.096787 3.537095]
[ 5.020007  6.415504 -0.197969]
[0.957999 7.17357  4.190265]
[6.434517 9.013406 3.437787]
[ 4.927675  6.316841 -0.289619]
[0.868655 7.077949 4.091206]
[6.344906 8.930025 3.338478]
[ 4.835343  6.218178 -0.38127 ]
[0.77931  6.982328 3.992147]
[6.255294 8.846645 3.239169]
[ 4.743012  6.119515 -0.47292 ]
[0.689965 6.886708 3.893088]
[6.165682 8.763264 3.139861]
[ 4.65068   6.020852 -0.56457 ]
[0.600621 6.791087 3.794028]
[6.076071 8.679883 3.040552]
[ 4.558348  5.922189 -0.65622 ]


In [10]:
positions[0,:,:]

array([[ 1.226033,  1.136689,  1.047344,  0.957999,  0.868655,  0.77931 ,
         0.689965,  0.600621,  0.511276,  0.421931,  0.332587,  0.243242,
         0.153897,  0.064553, -0.024792, -0.114137, -0.203481, -0.292826,
        -0.382171, -0.471515, -0.56086 , -0.650205, -0.739549, -0.828894,
        -0.918239, -1.007583, -1.096928, -1.186272, -1.275617, -1.364962,
        -1.454306, -1.543651, -1.632996, -1.72234 , -1.811685, -1.90103 ,
        -1.990374, -2.079719, -2.169064, -2.258408, -2.347753, -2.437098,
        -2.526442, -2.615787, -2.705132, -2.794476, -2.883821, -2.973166,
        -3.06251 , -3.151855],
       [ 7.460432,  7.364812,  7.269191,  7.17357 ,  7.077949,  6.982328,
         6.886708,  6.791087,  6.695466,  6.599845,  6.504224,  6.408603,
         6.312983,  6.217362,  6.121741,  6.02612 ,  5.930499,  5.834879,
         5.739258,  5.643637,  5.548016,  5.452395,  5.356774,  5.261154,
         5.165533,  5.069912,  4.974291,  4.87867 ,  4.78305 ,  4.687429,
       

In [52]:
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython import display 

fig, ax = plt.subplots()

def animate(i):
    ax.clear()
    ax.set_ylim(-15,15)
    ax.set_xlim(-15,15)
    for index in range(Nbody):
        pos = positions[index,:,i]
        ax.scatter(pos[0], pos[1], marker='o')


ani = FuncAnimation(fig, animate, frames=Nstep, interval=20, repeat=False)
video = ani.to_html5_video()
html = display.HTML(video)
display.display(html)
plt.close()