In [1]:
import os
import csv
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

In [36]:
def read_particle_positions(filename):
    positions = []
    with open(filename, 'r') as csvfile:
        csvreader = csv.reader(csvfile)
        next(csvreader)  # Skip header row
        for row in csvreader:
            positions.append([float(row[0]), float(row[1]), float(row[2])])
    return positions

In [47]:
directory = './output/default_simulation_params/'  # Directory containing CSV files
files = sorted([f for f in os.listdir(directory) if f.startswith('particle_positions')])

Nbody = 3
Ndim = 3
Nstep = 50
positions = np.empty((Nbody,Ndim,Nstep))

for f_index, file in enumerate(files):
    line = read_particle_positions(os.path.join(directory, file))
    for index in range(len(line)):
        positions[index,:,f_index] = line[index]
        print(positions[index,:,f_index])

[ 1.873067 11.23408   6.779752]
[10.089446 13.920393  5.652531]
[7.845503 9.967241 0.015473]
[ 1.773067 11.13408   6.679752]
[ 9.989446 13.820393  5.552531]
[ 7.745503  9.867241 -0.084527]
[ 1.673067 11.03408   6.579752]
[ 9.889446 13.720393  5.452531]
[ 7.645503  9.767241 -0.184527]
[ 1.573067 10.93408   6.479752]
[ 9.789446 13.620393  5.352531]
[ 7.545503  9.667241 -0.284527]
[ 1.473067 10.83408   6.379752]
[ 9.689446 13.520393  5.252531]
[ 7.445503  9.567241 -0.384527]
[ 1.373067 10.73408   6.279752]
[ 9.589446 13.420393  5.152531]
[ 7.345503  9.467241 -0.484527]
[ 1.273067 10.63408   6.179752]
[ 9.489446 13.320393  5.052531]
[ 7.245503  9.367241 -0.584527]
[ 1.173067 10.53408   6.079752]
[ 9.389446 13.220393  4.952531]
[ 7.145503  9.267241 -0.684527]
[ 1.073067 10.43408   5.979752]
[ 9.289446 13.120393  4.852531]
[ 7.045503  9.167241 -0.784527]
[ 0.973067 10.33408   5.879752]
[ 9.189446 13.020393  4.752531]
[ 6.945503  9.067241 -0.884527]
[ 0.873067 10.23408   5.779752]
[ 9.089446 

In [54]:
positions[0,:,:]

array([[ 1.873067,  1.773067,  1.673067,  1.573067,  1.473067,  1.373067,
         1.273067,  1.173067,  1.073067,  0.973067,  0.873067,  0.773067,
         0.673067,  0.573067,  0.473067,  0.373067,  0.273067,  0.173067,
         0.073067, -0.026933, -0.126933, -0.226933, -0.326933, -0.426933,
        -0.526933, -0.626933, -0.726933, -0.826933, -0.926933, -1.026933,
        -1.126933, -1.226933, -1.326933, -1.426933, -1.526933, -1.626933,
        -1.726933, -1.826933, -1.926933, -2.026933, -2.126933, -2.226933,
        -2.326933, -2.426933, -2.526933, -2.626933, -2.726933, -2.826933,
        -2.926933, -3.026933],
       [11.23408 , 11.13408 , 11.03408 , 10.93408 , 10.83408 , 10.73408 ,
        10.63408 , 10.53408 , 10.43408 , 10.33408 , 10.23408 , 10.13408 ,
        10.03408 ,  9.93408 ,  9.83408 ,  9.73408 ,  9.63408 ,  9.53408 ,
         9.43408 ,  9.33408 ,  9.23408 ,  9.13408 ,  9.03408 ,  8.93408 ,
         8.83408 ,  8.73408 ,  8.63408 ,  8.53408 ,  8.43408 ,  8.33408 ,
       

In [52]:
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython import display 

fig, ax = plt.subplots()

def animate(i):
    ax.clear()
    ax.set_ylim(-15,15)
    ax.set_xlim(-15,15)
    for index in range(Nbody):
        pos = positions[index,:,i]
        ax.scatter(pos[0], pos[1], marker='o')


ani = FuncAnimation(fig, animate, frames=Nstep, interval=20, repeat=False)
video = ani.to_html5_video()
html = display.HTML(video)
display.display(html)
plt.close()